/**
 * This class is generated by jOOQ
 */
package com.lrest.server.jooqmodel.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tusers implements Serializable {

    private static final long serialVersionUID = 1203201710;

    private Integer id;
    private String  name;
    private String  password;
    private String  token;

    public Tusers() {}

    public Tusers(Tusers value) {
        this.id = value.id;
        this.name = value.name;
        this.password = value.password;
        this.token = value.token;
    }

    public Tusers(
        Integer id,
        String  name,
        String  password,
        String  token
    ) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.token = token;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tusers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
